.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GREYDB" "8" "May 2016" "" ""
.
.SH "NAME"
\fBgreydb\fR \- greyd database tool
.
.SH "SYNOPSIS"
\fBgreydb\fR [\fB\-f\fR config] [[\fB\-TDt\fR] \fB\-a\fR keys] [[\fB\-TDt\fR] \fB\-d\fR keys] [\fB\-Y\fR synctarget]
.
.SH "DESCRIPTION"
\fBgreydb\fR manipulates the \fBgreyd\fR database used for \fBgreyd\fR(8)\.
.
.P
The options are as follows:
.
.TP
\fB\-f\fR \fIconfig\fR
The main greyd configuration file\.
.
.TP
\fB\-a\fR \fIkeys\fR
Add or update the entries for keys\. This can be used to whitelist one or more IP addresses (i\.e\. circumvent the greylisting process altogether) by adding all IP addresses as keys to the \fBgreyd\fR database for WHITE entries\. If any keys specified match entries already in the \fBgreyd\fR database, \fBgreydb\fR updates the entry\'s time last seen to now\.
.
.TP
\fB\-d\fR \fIkeys\fR
Delete entries for keys\.
.
.TP
\fB\-T\fR
Add or delete the keys as SPAMTRAP entries\. See the GREYTRAPPING section of \fBgreyd\fR(8) for more information\. Must be used in conjunction with the \fB\-a\fR or \fB\-d\fR option\.
.
.TP
\fB\-D\fR
Add or delete the keys as permitted DOMAIN entries\. See the GREYTRAPPING section of \fBgreyd\fR(8) for more information\. Must be used in conjunction with the \fB\-a\fR or \fB\-d\fR option\.
.
.TP
\fB\-t\fR
Add or delete the keys as TRAPPED entries\. See the GREYTRAPPING section of \fBgreyd\fR(8) for more information\. Must be used in conjunction with the \fB\-a\fR or \fB\-d\fR option\.
.
.TP
\fB\-Y\fR \fIsynctarget\fR
Add a target to receive synchronisation messages; see \fISYNCHRONISATION\fR below\. This option can be specified multiple times\.
.
.P
If adding or deleting a SPAMTRAP address (\fB\-T\fR), keys should be specified as email addresses:
.
.IP "" 4
.
.nf

spamtrap@mydomain\.org
.
.fi
.
.IP "" 0
.
.P
If adding or deleting a DOMAIN entries (\fB\-D\fR), keys should be specified as domains/email addresses:
.
.IP "" 4
.
.nf

allowed\-domain\.org
@another\-allowed\-domain\.org
individual@greyd\.org
.
.fi
.
.IP "" 0
.
.P
Otherwise keys must be numerical IP addresses\.
.
.SH "DATABASE OUTPUT FORMAT"
If invoked without any arguments, \fBgreydb\fR lists the contents of the database in a text format\.
.
.P
For SPAMTRAP and DOMAIN entries the format is:
.
.IP "" 4
.
.nf

type|mailaddress
.
.fi
.
.IP "" 0
.
.P
where type will be SPAMTRAP and mailaddress will be the email address for which any connections received by \fBgreyd\fR(8) will be blacklisted if mail is sent to this address\.
.
.P
For TRAPPED entries the format is:
.
.IP "" 4
.
.nf

type|ip|expire
.
.fi
.
.IP "" 0
.
.P
where \fItype\fR will be TRAPPED, IP will be the IP address blacklisted due to hitting a spamtrap, and \fIexpire\fR will be when the IP is due to be removed from the blacklist\.
.
.P
For GREY entries, the format is:
.
.IP "" 4
.
.nf

type|source IP|helo|from|to|first|pass|expire|block|pass
.
.fi
.
.IP "" 0
.
.P
For WHITE entries, the format is:
.
.IP "" 4
.
.nf

type|source IP|||first|pass|expire|block|pass
.
.fi
.
.IP "" 0
.
.P
The fields are as follows:
.
.TP
\fBtype\fR
WHITE if whitelisted or GREY if greylisted
.
.TP
\fBsource IP\fR
IP address the connection originated from
.
.TP
\fBhelo\fR
what the connecting host sent as identification in the HELO/EHLO command in the SMTP dialogue
.
.TP
\fBfrom\fR
envelope\-from address for GREY (empty for WHITE entries)
.
.TP
\fBto\fR
envelope\-to address for GREY (empty for WHITE entries)
.
.TP
\fBfirst\fR
time the entry was first seen
.
.TP
\fBpass\fR
time the entry passed from being GREY to being WHITE
.
.TP
\fBexpire\fR
time the entry will expire and be removed from the database
.
.TP
\fBblock\fR
number of times a corresponding connection received a temporary failure from \fBgreyd\fR(8)
.
.TP
\fBpass\fR
number of times a corresponding connection has been seen to pass to the real MTA by \fBgreylogd\fR(8)
.
.P
Note that times are in seconds since the Epoch, in the manner returned by time(3)\. Times may be converted to human readable format using:
.
.IP "" 4
.
.nf

$ date \-\-date \'@<value>\'
.
.fi
.
.IP "" 0
.
.SH "SYNCHRONISATION"
\fBgreydb\fR supports realtime synchronisation of added entries by sending the information it updates to a number of \fBgreyd\fR(8) daemons running on multiple machines\. To enable synchronisation, use the command line option \-Y to specify the machines to which \fBgreydb\fR will send messages\. The synchronisation may also be configured entirely via \fBgreyd\.conf\fR(5)\. For more information, see \fBgreyd\fR(8) and \fBgreyd\.conf\fR(5)\.
.
.P
\fBgreydb\fR only sends sync messages for additions/deletions of WHITE & TRAPPED entries only\.
.
.SH "COPYRIGHT"
\fBgreydb\fR is Copyright (C) 2015 Mikey Austin (greyd\.org)
.
.SH "SEE ALSO"
\fBgreyd\.conf\fR(5), \fBgreyd\-setup\fR(8), \fBgreyd\fR(8), \fBgreylogd\fR(8)
.
.SH "CREDITS"
Much of this man page was taken from the \fIOpenBSD\fR manual, and adapted accordingly\.
